[build]
  command = "next build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

# Add these specific function configurations
[functions.analyze-site]
  included_files = []
  timeout = "30s"

[functions.vibes-roast]
  included_files = []
  timeout = "30s"

# This is a catch-all for other functions
[functions."*"]
  timeout = "30s"