[build]
  command = "next build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[edge_functions]]
  function = "vibes-roast"
  path = "/api/vibes-roast"

[[edge_functions]]
  function = "analyze-site"
  path = "/api/analyze-site"

# Edge function settings
[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"

# Optional: Configure function settings
[functions]
  node_bundler = "esbuild"
  included_files = []

[functions."*"]
  timeout = "30s"