[build]
  command = "next build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

[functions."*"]
  timeout = 30

[build.environment]
  NODE_VERSION = "18"
