[build]
  command = "next build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@sparticuz/chrome-aws-lambda"]

[build.environment]
  NODE_VERSION = "18"

[functions."*"]
  timeout = 30
  memory = 1024