[build]
  command = "next build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[edge_functions]]
  function = "app/api/vibes-roast/route"
  path = "/api/vibes-roast"

[[edge_functions]]
  function = "app/api/analyze-site/route"
  path = "/api/analyze-site"

# Edge function settings
[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_FORCE_EDGE_RUNTIME = "true"

[functions]
  node_bundler = "esbuild"
  included_files = []
  external_node_modules = ["@anthropic-ai/sdk", "openai", "cheerio"]

[functions."*"]
  timeout = "30s"