[build]
  command = "next build && netlify deploy --build"
  publish = ".next"

[[redirects]]
  from = '/_next/image/*'
  query = { q = ':quality', url = ':url', w = ':width' }
  to = '/.netlify/images?url=:url&w=:width&q=:quality'
  status = 200
  force = true

[[plugins]]
  package = "@netlify/plugin-nextjs"


[[edge_functions]]
  function = "vibes-roast"
  path = "/api/vibes-roast"

[[edge_functions]]
  function = "analyze-site"
  path = "/api/analyze-site"

