[build]
  command = "next build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"

[functions."*"]
  timeout = 60  # Increased to 60 seconds
  memory = 2048  # Increased to 2GB