[build]
  command = "next build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

# Add edge function configuration
[[edge_functions]]
  path = "/api/*"
  function = "api"