[build]
  command = "next build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

# Target the Next.js server handler specifically
[functions.Next_js_Server_Handler]
  timeout = "30s"

# Backup catch-all
[functions."*"]
  timeout = "30s"