[build]
  command = "next build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

[functions."*"]
  timeout = 60
  memory = 2048

[build.environment]
  NODE_VERSION = "18"

[functions.vibes-roast]
  timeout = 60
  memory = 2048