import type { Metadata } from "next";
import "./globals.css"; // This now includes all the styles we need
import { FloatingNav } from "@/components/FloatingNav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head />
      <body>
        <FloatingNav />
        {children}
      </body>
    </html>
  );
}